version: '2'

services:

  redmine:
    image: redmine
#    ports:
#      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    volumes:
      - ./redmine_logs:/usr/src/redmine/log
    depends_on:
      - db
    restart: always

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    image: arvindr226/redmine 
    ports:
      - 80:80
    restart: always
